# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Proiect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commnent',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pronostic',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
